### ISSUE TITLE
Project help

### ISSUE THREAD

**Issue by markMichail** [bassemhossam/Video-Summarization#1]
good evening
I was asking if you had finished this project (built the models) and you can upload it because your project is similar to part of our graduation project.

thanks in advance

**Comment by bassemhossam** [comment]
Hi Mark,
Sorry for the late response but I had problems accessing my old files and it took some time to resolve , I have now uploaded the trained model here : https://drive.google.com/file/d/1KP10DjRl2XkYSPeGrLUktQVuce1_4CHK/view?usp=sharing
I hope this can help you in your project and best of luck.

**Comment by markMichail** [comment]
Thank you very much
