### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './meta_data/cider_jsons/gts_valid.pkl' + dataset

### ISSUE THREAD

**Issue by markMichail** [bassemhossam/Video-Summarization#2]
can you send me this file also?

sorry for interruption

and can you also tell me which dataset you used for training

**Comment by bassemhossam** [comment]
We built our project on the code base found in this repo :https://github.com/chitwansaharia/HACAModel , you will find those files there.
And Here is actually the paper that the model was adopted from which you might find helpful : https://arxiv.org/abs/1804.05448

**Comment by markMichail** [comment]
Thank you for your help
